const config = {
  CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS || "",
  ALCHEMY_ID: process.env.NEXT_PUBLIC_ALCHEMY_ID || "",
  GITHUB_CLIENT_ID: process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID || "",
  GITHUB_CLIENT_SECRET: process.env.NEXT_PUBLIC_GITHUB_CLIENT_SECRET || "",
  GITHUB_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_GITHUB_CONTRACT_ADDRESS || "",
  TWITTER_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_TWITTER_CONTRACT_ADDRESS || "",
  WALLET_CONNECT_PROJECTID:
    process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECTID || "",
  CIRCLE_API_KEY: process.env.NEXT_PUBLIC_CIRCLE_API_KEY || "",
  SUBGRAPH_URL: process.env.NEXT_PUBLIC_SUBGRAPH || "",
  BACKEND_API_URL: process.env.NEXT_PUBLIC_BACKEND_API_URL || "",
  TESTNET: process.env.NEXT_PUBLIC_TESTNET === "true" ? true : false,
};

export default config;
