export const LOCAL_STORAGE_GITHUB_CODE = "LOCAL_STORAGE_GITHUB_CODE";
export const LOCAL_STORAGE_GITHUB_ACCESS_TOKEN =
  "LOCAL_STORAGE_GITHUB_ACCESS_TOKEN";
export const LOCAL_STORAGE_TWITTER_ACCESS_TOKEN =
  "LOCAL_STORAGE_TWITTER_ACCESS_TOKEN";

export const CIRCLE_MATIC = "MATIC";
export const CIRCLE_USD = "USD";
